### ISSUE TITLE
max/min upload timestamp

### ISSUE THREAD

**Issue by jojenki** [openmhealth/developer#5]
Add two parameters (max_upload_timestamp and min_upload_timestamp).

**Comment by jshslsky** [comment]
IMO these parameters should default to inclusive bounds on the query.

**Comment by jojenki** [comment]
It was decided that this was one way to solve the problem but that other, better ways might exist. Also, this is probably not the normal use-case and that gappy data is unlikely. Therefore, for now, we are omitting this from the specification.

I will close this for now, but, if anyone has any other comments that they want to add or feels the need to reopen this, feel free to do so.
